export const routes = {
  signIn: "/sign-in",
  feed: "/feed",
  createPost: "/feed/create-post",
  forgotPassword: "forgot-password",
  callback: "/callback",
  resetPassword: "reset-password",
  requestResetPassword: "request-reset-password",
  superAdminPanel: "/super-admin-panel",
  crm: "/crm",
  crmContacts: "/crm/contacts",
  crmCompanies: "/crm/companies",
  crmCallHistory: "/crm/call-center",
  crmActivities: "/crm/activities",
  manufacturers: "/manufacturers",
  tech: "/tech",
  dispatch: "/dispatch",
  users: "/users",
  crmDocuments: "/crm/documents",
  crmJobs: "/crm/jobs",
  addJob: "/add-job",
  notFound: "/not-found",
  crmInsights: "/crm/insights",
  orderStatus: "/order-status",
  crmWebActivities: "/crm/web-activities"
};
