export enum ButtonVariant {
  PRIMARY_BG = "primary-bg",
  PRIMARY_OUTLINE = "primary-outline",
  PRIMARY_NUDE = "primary-nude",
  WARNING_BG = "warning-bg",
  WARNING_OUTLINE = "warning-outline",
  WARNING_NUDE = "warning-nude",
  ERROR_BG = "error-bg",
  ERROR_OUTLINE = "error-outline",
  ERROR_NUDE = "error-nude",
  DEFAULT_BG = "default-bg",
  DEFAULT_OUTLINE = "default-outline",
  DEFAULT_NUDE = "default-nude",
  DISABLE_BG = "disabled-bg",
  DISABLE_OUTLINE = "disabled-outline",
  DISABLE_NUDE = "disabled-nude",
  TAB_SELECTED = "tab-selected",
}
